name: Build APK

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Unzip Project and Locate Root
        run: |
          mkdir -p my_project
          unzip -q WhatsAppRecoveryPro-CLOUD-READY-v2.zip -d my_project
          # البحث تلقائياً عن مجلد المشروع الذي يحتوي على gradlew
          GRADLEW_FILE=$(find my_project -name "gradlew" -print -quit)
          PROJECT_DIR=$(dirname "$GRADLEW_FILE")
          echo "PROJECT_DIR=$PROJECT_DIR" >> $GITHUB_ENV
          echo "Found project at: $PROJECT_DIR"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant execute permission and fix line endings
        run: |
          chmod +x ${{ env.PROJECT_DIR }}/gradlew
          find ${{ env.PROJECT_DIR }} -type f -exec sed -i 's/\r$//' {} +

      - name: Build APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: My-App-APK
          path: ${{ env.PROJECT_DIR }}/app/build/outputs/apk/debug/*.apk
          
